# Import essential libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data Loading

In [2]:
books = pd.read_csv('Books.csv')
users = pd.read_csv('Users.csv')
ratings = pd.read_csv('Ratings.csv')

C:\Users\kg834\AppData\Local\Temp\ipykernel_20016\1748781244.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

# Data Analysis

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
books.shape

(271360, 8)

In [5]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [6]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher', 'Image-URL-L']]

In [7]:
books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...

In [8]:
# rename names of columns

books.rename(columns={
    "Book-Title": "Title",
    "Book-Author": "Author",
    "Year-Of-Publication": "Year",
    "Publisher": "Publisher",
    "Image-URL-L": "img_url"  },
      inplace = True
)

In [9]:
books.head(2)

,ISBN,Title,Author,Year,Publisher,img_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...

In [10]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [11]:
users.shape

(278858, 3)

In [12]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [13]:
ratings.shape

(1149780, 3)

In [14]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 6)
(278858, 3)
(1149780, 3)

In [15]:
ratings.rename( columns={
    "User-ID" : "User_id",
    "Book-Rating" : "Rating"},
      inplace = True    
)

In [16]:
ratings.head(2)

   User_id        ISBN  Rating
0   276725  034545104X       0
1   276726  0155061224       5

In [17]:
ratings['User_id'].value_counts()

User_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
119573        1
276706        1
276697        1
276679        1
276676        1
Name: count, Length: 105283, dtype: int64

In [18]:
ratings['User_id'].unique().shape

(105283,)


# Popular Based Recommender System

In [19]:
ratings_with_books = ratings.merge(books,on= "ISBN" )
ratings_with_books.head()

,User_id,ISBN,Rating,Title,Author,Year,Publisher,img_url
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...

In [20]:
ratings_with_books.shape

(1031136, 8)

In [21]:
num_rating = ratings_with_books.groupby('Title').count()['Rating'].reset_index()
num_rating.rename(columns = {
    "Rating" : "num_rating"},
    inplace = True)
num_rating.head()

                                               Title  num_rating
0   A Light in the Storm: The Civil War Diary of ...           4
1                              Always Have Popsicles           1
2               Apple Magic (The Collector's series)           1
3   Ask Lily (Young Women of Faith: Lily Series, ...           1
4   Beyond IBM: Leadership Marketing and Finance ...           1

In [22]:
avg_rating = ratings_with_books.groupby('Title')['Rating'].mean().reset_index()

avg_rating.rename(columns = {
    "Rating" : "avg_rating"},
    inplace = True)
avg_rating.head()

                                               Title  avg_rating
0   A Light in the Storm: The Civil War Diary of ...        2.25
1                              Always Have Popsicles        0.00
2               Apple Magic (The Collector's series)        0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...        8.00
4   Beyond IBM: Leadership Marketing and Finance ...        0.00

In [23]:
popular_df = num_rating.merge(avg_rating,on='Title')
popular_df.head()

                                               Title  num_rating  avg_rating
0   A Light in the Storm: The Civil War Diary of ...           4        2.25
1                              Always Have Popsicles           1        0.00
2               Apple Magic (The Collector's series)           1        0.00
3   Ask Lily (Young Women of Faith: Lily Series, ...           1        8.00
4   Beyond IBM: Leadership Marketing and Finance ...           1        0.00

In [24]:
popular_df = popular_df[popular_df['num_rating']>=250].sort_values('avg_rating',ascending=False).head(50)

In [25]:
final_df = popular_df.merge(books,on='Title').drop_duplicates('Title')[['Title','Author','num_rating','avg_rating','img_url']]

In [26]:
final_df

,Title,Author,num_rating,avg_rating,img_url
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,428,5.852804,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,387,5.824289,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,278,5.737410,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,347,5.501441,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,556,5.183453,http://images.amazon.com/images/P/0439064872.0...
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,281,5.007117,http://images.amazon.com/images/P/0345339681.0...
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,368,4.948370,http://images.amazon.com/images/P/0345339703.0...
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,575,4.895652,http://images.amazon.com/images/P/059035342X.0...
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,260,4.880769,http://images.amazon.com/images/P/0345339711.0...
39,To Kill a Mockingbird,Harper Lee,510,4.700000,http://images.amazon.com/images/P/0446310786.0...
47,The Da Vinci Code,Dan Brown,898,4.642539,http://images.amazon.com/images/P/0385504209.0...
53,The Five People You Meet in Heaven,Mitch Albom,430,4.551163,http://images.amazon.com/images/P/0786868716.0...
55,The Catcher in the Rye,J.D. Salinger,449,4.545657,http://images.amazon.com/images/P/0316769487.0...
62,The Lovely Bones: A Novel,Alice Sebold,1295,4.468726,http://images.amazon.com/images/P/0316666343.0...
63,1984,George Orwell,284,4.454225,http://images.amazon.com/images/P/0451524934.0...
72,Prodigal Summer: A Novel,Barbara Kingsolver,253,4.450593,http://images.amazon.com/images/P/0060959037.0...
73,Neverwhere,Neil Gaiman,265,4.449057,http://images.amazon.com/images/P/0380789019.0...
78,The Secret Life of Bees,Sue Monk Kidd,774,4.447028,http://images.amazon.com/images/P/0142001740.0...
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,283,4.356890,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,493,4.354970,http://images.amazon.com/images/P/0385484518.0...
88,The Red Tent (Bestselling Backlist),Anita Diamant,723,4.334716,http://images.amazon.com/images/P/0312195516.0...
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,268,4.328358,http://images.amazon.com/images/P/0671461494.0...
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,335,4.289552,http://images.amazon.com/images/P/0805063897.0...
100,Into the Wild,Jon Krakauer,252,4.273810,http://images.amazon.com/images/P/0385486804.0...
103,Fahrenheit 451,Ray Bradbury,409,4.264059,http://images.amazon.com/images/P/3257208626.0...
116,Girl with a Pearl Earring,Tracy Chevalier,526,4.218631,http://images.amazon.com/images/P/0452282152.0...
117,Outlander,DIANA GABALDON,283,4.173145,http://images.amazon.com/images/P/0440222915.0...
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,585,4.105983,http://images.amazon.com/images/P/0446672211.0...
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,275,4.098182,http://images.amazon.com/images/P/0449005615.0...
126,Life of Pi,Yann Martel,664,4.088855,http://images.amazon.com/images/P/0151008116.0...
130,The Bean Trees,Barbara Kingsolver,389,4.087404,http://images.amazon.com/images/P/0060915544.0...
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,265,4.086792,http://images.amazon.com/images/P/1558743669.0...
135,ANGELA'S ASHES,Frank McCourt,279,4.075269,http://images.amazon.com/images/P/0684874350.0...
137,Good in Bed,Jennifer Weiner,490,4.055102,http://images.amazon.com/images/P/0743418174.0...
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,321,4.037383,http://images.amazon.com/images/P/0060938455.0...
140,American Gods,Neil Gaiman,302,4.006623,http://images.amazon.com/images/P/0380789035.0...
141,Skipping Christmas,JOHN GRISHAM,322,4.006211,http://images.amazon.com/images/P/0385505833.0...
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,318,4.003145,http://images.amazon.com/images/P/0842329129.0...
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,336,4.000000,http://images.amazon.com/images/P/037582345X.0...
157,The Color Purple,Alice Walker,314,3.964968,http://images.amazon.com/images/P/0671617028.0...
163,Silence of the Lambs,Thomas Harris,256,3.960938,http://images.amazon.com/images/P/0312924585.0...
166,About a Boy,Nick Hornby,262,3.900763,http://images.amazon.com/images/P/1573227331.0...
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,278,3.888489,http://images.amazon.com/images/P/0312265840.0...
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,266,3.875940,http://images.amazon.com/images/P/0062502174.0...
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,269,3.825279,http://images.amazon.com/images/P/0312983867.0...
182,Suzanne's Diary for Nicholas,James Patterson,457,3.820569,http://images.amazon.com/images/P/0316969443.0...
186,Lord of the Flies,William Gerald Golding,259,3.818533,http://images.amazon.com/images/P/0399501487.0...
192,A Prayer for Owen Meany,John Irving,413,3.796610,http://images.amazon.com/images/P/0345361792.0...
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,301,3.777409,http://images.amazon.com/images/P/0345313860.0...
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,356,3.772472,http://images.amazon.com/images/P/0316284955.0...

In [27]:
final_df['img_url'][0]

'http://images.amazon.com/images/P/0439136350.01.LZZZZZZZ.jpg'

# Collaborative Filtering Based Recommender System

In [28]:
x = ratings_with_books.groupby('User_id').count()['Rating'] > 200
edu_users = x[x].index
edu_users

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User_id', length=811)

In [29]:
filtered_rating = ratings_with_books[ratings_with_books['User_id'].isin(edu_users)]

In [30]:
y = filtered_rating.groupby('Title').count()['Rating']>=50
famous_books = y[y].index

In [31]:
final_ratings = filtered_rating[filtered_rating['Title'].isin(famous_books)]

In [32]:
pt = final_ratings.pivot_table(index='Title',columns='User_id',values='Rating')

In [33]:
pt.fillna(0,inplace= True)

In [34]:
pt

User_id,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

# Modelling

In [35]:
from scipy.sparse import csr_matrix
book_sparse = csr_matrix(pt)
book_sparse

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14289 stored elements and shape (706, 810)>

In [36]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [37]:
distance,suggestion = model.kneighbors(pt.iloc[237,:].values.reshape(1,-1),n_neighbors=6)

In [38]:
distance

array([[ 0.        , 29.30870178, 30.01666204, 30.41381265, 30.47950131,
        30.87069808]])

In [39]:
suggestion

array([[237, 357, 652, 175, 308, 142]])

In [40]:
for i in range(len(suggestion)):
    print(pt.index[suggestion[i]])

Index(['Hearts In Atlantis', 'No Safe Place',
       'Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))',
       'Exclusive', 'Long After Midnight',
       'Deck the Halls (Holiday Classics)'],
      dtype='object', name='Title')

In [41]:
pt.index[3]

'4 Blondes'

In [42]:
books_name = pt.index

In [57]:
import pickle
pickle.dump(model,open('model.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(final_ratings,open('final_rating.pkl','wb'))
pickle.dump(pt,open('pivot_table.pkl','wb'))
pickle.dump(final_df,open('final.pkl','wb'))

# test

In [54]:
def recommend(book_name):
    # index fetch
    book_id = np.where(pt.index==book_name)[0][0]
    distance,suggestion = model.kneighbors(pt.iloc[book_id,:].values.reshape(1,-1),n_neighbors=6)
    data = []
    for i in suggestion:
        item = []
        temp_df = books[books['Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Title')['Title'].values))
        item.extend(list(temp_df.drop_duplicates('Title')['Author'].values))
        item.extend(list(temp_df.drop_duplicates('Title')['img_url'].values))

        data.append(item)

    return data

In [55]:
recommend('1984')

[['1984',
  'George Orwell',
  'http://images.amazon.com/images/P/0451524934.01.LZZZZZZZ.jpg']]